stack=[]
stack.append('a')
stack.append('b')
stack.append('c')
print("initial stack")
print(stack)
print("elements popped from stack")
print(stack.pop())
print(stack.pop())
print(stack.pop())
print("stack after elements are popped")
print(stack)
